### ISSUE TITLE
Movement is correctly predicted/interpolated between client and server

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#121]

**Comment by AdamTadeusz** [comment]
This is a broad issue. Generally I think player position and speeds are correctly predicted now (although we are missing the ability to sprint while ducked and maybe sprint while walking?). One problem that we still have is with the pitch, yaw and roll of the lower and upper body. Likely caused by the player inheriting both a CPlayerAnimState from hl2mp_player and a CBasePlayerAnimState (through INeoPlayerAnimstate somehow?)

**Comment by AdamTadeusz** [comment]
A general overhaul of the player animations, maybe to be more in-line with Tonysergi's fixes where there is a single source of truth on either the client or server and where the other inherits from the source should fix this (and maybe also the original upper body animations workflow)

**Comment by AdamTadeusz** [comment]
I'm gonna unassign myself from this. I had a look and I could probably get it working at some point but I welcome others to have a crack at it instead.

**Comment by blaberry** [comment]
This issue would benefit greatly from a better problem statement and proposed solution, iirc it does point to a specific issue of animations swapping between two different states under some certain conditions, but as it stands it's overly broad.
