### ISSUE TITLE
TKs penalizes the player

### ISSUE THREAD

**Issue by blaberry** [NeotokyoRebuild/neo#220]
In ognt, a plugin exists that kills you if you attempt to teamkill in spawn/within the first ten seconds from round start.

**Comment by nullsystem** [comment]
Need details, kill the TKer on first 10secs of round?

**Comment by nullsystem** [comment]
If this is about XP to be taken away, this is already done back in 2020: https://github.com/NeotokyoRebuild/neo/commit/96c532d6668ace939f9657a3e91678b35b1b7f97

**Comment by kassibuss** [comment]
the issue is describing the behavior of the nt_mirrordamage plugin by soft

"For first 7 seconds of /.../ attackers will take double damage they inflicted and victim will not lose any health"

https://github.com/softashell/nt-sourcemod-plugins/blob/master/scripting/nt_mirrordamage.sp

In vanilla NT, i think you just get kickbanned from the server after an x amount of teamkills/damage at the start? Maybe some oldhead remembers better

**Comment by Agiel** [comment]
Vanilla NT has a cvar for mirror damage. There's also a cvar that bans you after a set number of team damage. Not sure how much exactly, or if it's a combination of damage and kills.

The latter has a bug where, when disabled, you get positive XP instead of negative from team kills.
