### ISSUE TITLE
Ghost cant be capped twice

### ISSUE THREAD

**Issue by StellaNova522** [NeotokyoRebuild/neo#229]
Just set a bool, right? how hard can it be :) - The Blå Berry

**Comment by blaberry** [comment]
I don't actually remember how to trigger this, I think it's by capturing the ghost, then dropping it, then picking it up again. Maybe you needed to bring it out and then into the cap zone?
@Rainyan you might remember this?

**Comment by Rainyan** [comment]
> I don't actually remember how to trigger this, I think it's by capturing the ghost, then dropping it, then picking it up again. Maybe you needed to bring it out and then into the cap zone? @Rainyan you might remember this?

Do you mean in OG NT? It happens if you're holding the ghost inside an enemy capzone radius when the round rolls over to the next. I haven't verified the details, but I'm assuming what roughly happens is:

* A new round begins
* Capzone ownership info for NSF<->Jinrai is flipped
* Some check somewhere (a gamerules think probably?) triggers *before* the ghost is reset, and:
  1. You're currently holding the ghost
  2. You're currently standing inside a capzone radius
  3. That capzone is currently marked as your team's capzone
* Therefore, you have just instantly capped the ghost

**Comment by nullsystem** [comment]
I swear this GH issue feels like it been filed assuming it has OG:NT behavior rather than actual behavior. Nevertheless I have seen a **visual** issue where it'll popup another ghost capture win HUD on moving to the 2nd cap zone in a short time (easy to do in oilstain), but in NT;RE, it doesn't alter the points at least.

**Comment by AdamTadeusz** [comment]
Can also trigger the "x captured the ghost" message when taking the ghost to a capture point after killing the enemy team first

**Comment by nullsystem** [comment]
I think this issue be closed in favor of this: https://github.com/NeotokyoRebuild/neo/issues/513
Considering the ghost can't even be capped twice (as in XP/Scores change) in the first place.
