### ISSUE TITLE
[BUG] Your viewmodel for other weapons is mirrored onto the top of the screen 

### ISSUE THREAD

**Issue by kassibuss** [NeotokyoRebuild/neo#420]
### Build Info

Build datetime: 2024-06-29T16:37:06Z Git hash: 96f57bed41f9607377521292c952d691696270d0

### Description

When playing in a server with people, your viewmodel is mirrored onto the top of your screen.

### To Reproduce

1. Join a server with players
2. Spawn in

### Expected behavior

You should not have anything related to your viewmodel on top of your view

### Actual behavior

There is a "ghost" of your viewmodel on top of your screen.

### Operating System

- [X] Windows
- [x] Linux

### Version/Distro

Windows 10

### Additional context and Screenshots
![image](https://github.com/NeotokyoRebuild/neo/assets/81193965/33e9a2b7-05e3-4fbb-aaed-cdc16197901a)

**Comment by Rainyan** [comment]
If this is exclusive to the Tachi, then this is a duplicate: #365

**Comment by Agiel** [comment]
I've seen legs also, probably the same issue? Could it have to do with the first person ragdolls?

**Comment by AdamTadeusz** [comment]
I think this is strictly happening with thrown weapons, beginning with when I added weapons being attached to actors rather than simply receiving the NO_DRAW flag when holstered. Also of not is that these incorrect viewmodels disappear after cyclign through all weapons. Whatever decides when a viewmodel for throwables should be drawn needs some tweaking I guess
