### ISSUE TITLE
Assists in killfeed should have a clearer separator

### ISSUE THREAD

**Issue by Agiel** [NeotokyoRebuild/neo#442]
### Build Info

20240629_321f139

### Description

The current separator (some sort of minus sign in a circle?) has the same color as the killer which makes the names blend together. The text color should be white and probably use a regular +.

### To Reproduce

Need one player to hurt an enemy 50+ damage, and then have another player make the killing blow.

### Expected behavior

I can tell who's the killer and who's giving the assist.

### Actual behavior

The kill feed is a mess.

### Operating System

- [X] Windows
- [ ] Linux

### Version/Distro

Windors 10

**Comment by nullsystem** [comment]
The ASCII `+` is used, it's more like the font need to change since it differs from OGNT's killfeed font.
![killfeed_OGNT](https://github.com/NeotokyoRebuild/neo/assets/15316579/fe3ed513-36a2-4a85-ad8f-6644b9a0accc)
![killfeed_NTRE](https://github.com/NeotokyoRebuild/neo/assets/15316579/c58a876c-560a-4eb3-93af-1adb5238c78e)
