### ISSUE TITLE
[FEATURE] Reach out to rschetype about avtomat4

### ISSUE THREAD

**Issue by StellaNova522** [NeotokyoRebuild/neo#690]
### Description

Reach out to rschetype about avtomat4 Remix

### Proposed Solution

Someone? should reach out to Rchetype and see if we can use therir music for NT;Re and we like the Avtomat4 remix made by Rchetype. (Making this issue for Blaberry, i have not really been keeping up so just making the issue with the info i have :p )

**Comment by AdamTadeusz** [comment]
I think the Haka remix by submerger is also amazing, although it probably doesn't fit into the main menu as well, or any other place in the game. Might be worth making a general issue to reach out to as many people that remixed music from the game, since there's no guarantee anyone will answer or agree
