### ISSUE TITLE
Can see own viewmodel after dying and spectating someone else, in the spot where you originally died

### ISSUE THREAD

**Issue by AdamTadeusz** [NeotokyoRebuild/neo#720]

**Comment by Rainyan** [comment]
Reproduction steps:

```
map nt_dimensions_test
bot_add
bot_attack 0
bot_mimic 1
bot_mimic_yaw_offset 90
```

* Stand at a perpendicular aim angle to the bot
* Shoot your gun, so that the bot mimics it and damages you
* Die to the bot and observe the viewmodel behaviour upon death
  * Also try pressing the space bar to toggle spec modes during this sequence

What should happen:

* Your viewmodel is not visible after you've died

What happens:

* Your viewmodel is visible after you've died
